package tn.esprit.assistant;

public enum AssistantIntentType {
    UNKNOWN,
    CURRENT_SCREEN,
    SCREEN_HELP,
    MATCH_SCORERS,
    MATCH_ASSISTS,
    MATCH_WINNER,
    MATCH_SCORE,
    MATCH_CARDS,
    MATCH_STATISTICS,
    MATCH_LINEUP,
    MATCH_MVP,
    MATCH_SUMMARY,
    PLAYER_PROFILE_SUMMARY,
    PLAYER_AGE,
    PLAYER_NATIONALITY,
    PLAYER_CLUB,
    PLAYER_POSITION,
    PLAYER_SEASON_STATS,
    PLAYER_RECENT_FORM,
    SAFE_ACTION,
    RISKY_ACTION,
    CONFIRMATION,
    CANCELLATION
}
